### ISSUE TITLE
Преобразует "Привет" в "privet?"

### ISSUE THREAD

**Issue by mezhevikin** [Macseam/TranslitRusEng#2]
Привет. Спасибо за скрипт.
Нашел баг. Скрипт преобразует строку "Привет" в "privet?" тем самым игнорируя большие буквы. Можно ли как-то это исправить?

**Comment by Macseam** [comment]
@mezhevikin рад, что скрипт пригодился! Доработал приведение к нижнему регистру, теперь без опции lowerCase регистр изменяться не будет. Надо обновить версию скрипта на 1.0.8 и передавать options как объект (в ридми подробнее написано).

**Comment by mezhevikin** [comment]
@Macseam спасибо!
